In [246]:
import pandas as pd
import numpy as np

In [247]:
pd.set_option('display.max_columns', None)
three_df = pd.read_csv('ThreeSubjectheadings.csv')
one_df = pd.read_csv('OneSubjectHeading.csv')

In [248]:
# rename columns
one_df = one_df.rename(columns={'Title (Complete)' : 'Title',
                   'Permanent Call Number' : 'Call Number',
               'Loan Date' : 'Date'})

#convert to string and change year to whole year
one_df['Date'] = one_df['Date'].astype(str).str[-4:]
one_df.head(5)

,Item Loan Id,Date,In House Loan Indicator,Barcode,Call Number,Circulation Library Code,Owning Library Code,Title,Author,Subjects,MMS Id,Subjects (Names)
0,2252958767220001701,2018,N,31951D01848189P,HT119 .S65 2000,TARCH,TARCH,Postmetropolis : critical studies of cities an...,"Soja, Edward W.",Cities and towns,9913933350001701,NaN
1,2252959196040001701,2018,N,31951000140967E,E159 .H77,TARCH,TARCH,Presence of the past ; a history of the preser...,"Hosmer, Charles Bridgham, 1932-",Monuments--Conservation and restoration--Unite...,9930689970001701,NaN
2,2252965815260001701,2018,N,31951P012191854,Unknown,TARCH,TARCH,Topos : European landscape magazine.,NaN,Landscape architecture--Europe--Periodicals.,9929887730001701,NaN
3,2252965816190001701,2018,N,31951P012191862,Unknown,TARCH,TARCH,Topos : European landscape magazine.,NaN,Landscape architecture--Europe--Periodicals.,9929887730001701,NaN
4,2252965817370001701,2018,N,31951P012055993,Unknown,TARCH,TARCH,Topos : European landscape magazine.,NaN,Landscape architecture--Europe--Periodicals.,9929887730001701,NaN

In [249]:
# rename columns
three_df = three_df.rename(columns={'Title (Complete)' : 'Title',
                   'Permanent Call Number' : 'Call Number',
               'Loan Date' : 'Date'})

#convert to string and change year to whole year
three_df['Date'] = three_df['Date'].astype(str).str[-4:]
three_df.head(5)

,Item Loan Id,Date,In House Loan Indicator,Barcode,Call Number,Circulation Library Code,Owning Library Code,Title,Author,Subjects,MMS Id,Subjects (Names)
0,2252958767220001701,2018,N,31951D01848189P,HT119 .S65 2000,TARCH,TARCH,Postmetropolis : critical studies of cities an...,"Soja, Edward W.",Cities and towns,9.913933e+15,NaN
1,2252958767220001701,2018,N,31951D01848189P,HT119 .S65 2000,TARCH,TARCH,Postmetropolis : critical studies of cities an...,"Soja, Edward W.",Metropolitan areas,9.913933e+15,NaN
2,2252958767220001701,2018,N,31951D01848189P,HT119 .S65 2000,TARCH,TARCH,Postmetropolis : critical studies of cities an...,"Soja, Edward W.",Urbanization,9.913933e+15,NaN
3,2252959196040001701,2018,N,31951000140967E,E159 .H77,TARCH,TARCH,Presence of the past ; a history of the preser...,"Hosmer, Charles Bridgham, 1932-",Monuments--Conservation and restoration--Unite...,9.930690e+15,NaN
4,2252959196040001701,2018,N,31951000140967E,E159 .H77,TARCH,TARCH,Presence of the past ; a history of the preser...,"Hosmer, Charles Bridgham, 1932-",Historic buildings--United States,9.930690e+15,NaN

In [250]:
# get the number of unique loan records because loans were multiplied due to breaking up subject headings
unique_loans = three_df['Item Loan Id'].nunique()
unique_loans
t = three_df[(three_df['Subjects'] == 'Architecture--Spain--Periodicals.')]
t2023 = t[t['Date'] == '2023']
t2018 = t[t['Date'] == '2018']
len(t2023) - len(t2018) 
unique_loans

20588

In [257]:
unique_loans_2023 = three_df.copy()
unique_loans_2023 = unique_loans_2023[unique_loans_2023['Date'] == '2023']
unique_loans_2023 = unique_loans_2023.nunique()
unique_loans_2023

Item Loan Id                2577
Date                           1
In House Loan Indicator        1
Barcode                     2176
Call Number                 2098
Circulation Library Code      12
Owning Library Code            1
Title                       2115
Author                      1373
Subjects                    3505
MMS Id                      2119
Subjects (Names)             457
dtype: int64

In [258]:
def YearLoanNumber(df, Date):
    df = df.copy()
    df = df[df['Date'] == Date]
    distinct_loan_number = df['Item Loan Id'].nunique()
    return distinct_loan_number

In [259]:
YearLoanNumber(three_df, '2023')

2577

In [260]:
def SubjectHeadingoverlaps(df, SubjectHeading1, SubjectHeading2, Date):
    df = df.copy()
    df = df[(df['Subjects'] == SubjectHeading1) | (df['Subjects'] == SubjectHeading2)]
    df = df[df['Date'] == Date]
    duplicates = df['Item Loan Id'].value_counts() == 1
    duplicates_num = duplicates.sum() 
    print('There are:', len(df), 'rows with', duplicates_num, 'Overlap')

    #unique_loans = df['Item Loan Id'].nunique()
    #print("These two headings overlap:", len(df)-unique_loans, "times")
    #overlaps = len(df)-unique_loans
    #return overlaps

In [261]:
SubjectHeadingoverlaps(three_df,'Architecture--Spain--Periodicals.', 'Architecture--Espagne--20e siècle--Périodiques.', '2023')

There are: 194 rows with 0 Overlap

In [ ]:
# Create a mask to subset data by year
def Mask(year, df):
    mask_year = df[(df.Date == year)]
    return(mask_year)

In [ ]:
def DiffPerc(df, sort_year, order):
    # This function inputs a dataframe, and then groupsby count values for each subject and year. 
    # It then converts those subject heading counts into a percentage of all counts for a year by dividing each subject heading by total checkout counts for the year.
    # It then merges all of these new columns into a new dataframe 
    
    # use mask function to subset by year
    subset_2018 = Mask('2018', df)
    subset_2019 = Mask('2019', df)
    subset_2020 = Mask('2020', df)
    subset_2021 = Mask('2021', df)
    subset_2022 = Mask('2022', df)
    subset_2023 = Mask('2023', df)
    
    # group by counts for every year and subject
    counts_2018 = subset_2018.groupby(['Subjects', 'Date']).size().reset_index(name='Counts').sort_values(by=['Counts'], ascending=[False])
    counts_2019 = subset_2019.groupby(['Subjects', 'Date']).size().reset_index(name='Counts').sort_values(by=['Counts'], ascending=[False])
    counts_2020 = subset_2020.groupby(['Subjects', 'Date']).size().reset_index(name='Counts').sort_values(by=['Counts'], ascending=[False])
    counts_2021 = subset_2021.groupby(['Subjects', 'Date']).size().reset_index(name='Counts').sort_values(by=['Counts'], ascending=[False])
    counts_2022 = subset_2022.groupby(['Subjects', 'Date']).size().reset_index(name='Counts').sort_values(by=['Counts'], ascending=[False])
    counts_2023 = subset_2023.groupby(['Subjects', 'Date']).size().reset_index(name='Counts').sort_values(by=['Counts'], ascending=[False])
    
     # create total checkouts variable for every year
    checkouts2018 = counts_2018['Counts'].sum()
    checkouts2019 = counts_2019['Counts'].sum()
    checkouts2020 = counts_2020['Counts'].sum()
    checkouts2021 = counts_2021['Counts'].sum()
    checkouts2022 = counts_2022['Counts'].sum()
    checkouts2023 = counts_2023['Counts'].sum()

    # create counts variable for every year

    counts_2018['Subj %'] = counts_2018['Counts'] / checkouts2018

    counts_2019['Subj %'] = counts_2019['Counts'] / checkouts2019
 
    counts_2020['Subj %'] = counts_2020['Counts'] / checkouts2020
 
    counts_2021['Subj %'] = counts_2021['Counts'] / checkouts2021
 
    counts_2022['Subj %'] = counts_2022['Counts'] / checkouts2022
 
    counts_2023['Subj %'] = counts_2023['Counts'] / checkouts2023
    
    # merge columns into a singular dataframe
    merged_df = pd.merge(counts_2018, counts_2019, how='left', on='Subjects')
    merged_df = merged_df.rename(columns={'Date_x' : 'Date 2018',
                    'Counts_x' : 'Counts 2018',
                'Subj %_x' : 'Subj % 2018',
                'Date_y' : 'Date 2019',
                    'Counts_y' : 'Counts 2019',
                'Subj %_y' : 'Subj % 2019'})
    
    merged_df2 = pd.merge(merged_df, counts_2020, how='left', on='Subjects')
    merged_df2 = merged_df2.rename(columns={'Date' : 'Date 2020',
                    'Counts' : 'Counts 2020',
                'Subj %' : 'Subj % 2020'})
    
    merged_df3 = pd.merge(merged_df2, counts_2021, how='left', on='Subjects')
    merged_df3 = merged_df3.rename(columns={'Date' : 'Date 2021',
                    'Counts' : 'Counts 2021',
                'Subj %' : 'Subj % 2021'})
    
    merged_df4 = pd.merge(merged_df3, counts_2022, how='left', on='Subjects')
    merged_df4 = merged_df4.rename(columns={'Date' : 'Date 2022',
                    'Counts' : 'Counts 2022',
                'Subj %' : 'Subj % 2022'})
    
    merged_df5 = pd.merge(merged_df4, counts_2023, how='left', on='Subjects')
    merged_df5 = merged_df5.rename(columns={'Date' : 'Date 2023',
                    'Counts' : 'Counts 2023',
                'Subj %' : 'Subj % 2023'})
    
    # subset df
    merged_df5 =merged_df5[['Subjects', 'Subj % 2018', 'Subj % 2019', 'Subj % 2020', 'Subj % 2021', 'Subj % 2022', 'Subj % 2023']]

    # create new column that measures subject heading growth as a decimal by substracting subject % 2023 -  subject # 2018
    merged_df5['2023 Diff 2018'] = merged_df5['Subj % 2023'] - merged_df5['Subj % 2018']
    merged_df5['2023 Diff 2020'] = merged_df5['Subj % 2023'] - merged_df5['Subj % 2020']
    merged_df5['2022 Diff 2018'] = merged_df5['Subj % 2022'] - merged_df5['Subj % 2018']
    merged_df5['2021 Diff 2018'] = merged_df5['Subj % 2021'] - merged_df5['Subj % 2018']
    merged_df5['2020 Diff 2018'] = merged_df5['Subj % 2020'] - merged_df5['Subj % 2018']
    merged_df5['2019 Diff 2018'] = merged_df5['Subj % 2019'] - merged_df5['Subj % 2018']

    # function to enable a sort year and ascending or deescending
    merged_df5 = merged_df5.sort_values(by=[sort_year], ascending=[order]).reset_index(drop=True)

    # reorder the columns
    merged_df5 = merged_df5[['Subjects', 'Subj % 2018', 'Subj % 2019', 'Subj % 2020', 'Subj % 2021', 'Subj % 2022', 'Subj % 2023', 
                             '2019 Diff 2018', '2020 Diff 2018','2021 Diff 2018', '2022 Diff 2018',  '2023 Diff 2018', '2023 Diff 2020']]

  
    return merged_df5

In [ ]:
# Utilized DiffPerc function to create dataframe that generates growth statistics for each subject heading 
# This dataset is from the version that utilizes the first three subject headings
# Sorted  by 2023 Diff 2018 on all there subjects (largest to smallest positive change)
# Percentages are not actually a percentage. It is a decimal.
diff_three_df2023 = DiffPerc(three_df, '2023 Diff 2018', False)
diff_three_df2023.head()

In [ ]:
# Utilized DiffPerc function to create dataframe that generates growth statistics for each subject heading 
# This dataset is from the version that utilizes only the first subject heading
# Sorted  by 2023 Diff 2018 on all there subjects (largest to smallest positive change)
# We didn't end up using this one.
diff_one_df2023 = DiffPerc(one_df, '2023 Diff 2018', False)
diff_one_df2023.head()

In [ ]:
# Compare Three subject heading vs one subject heading data
three2020 = diff_three_df2023 
three2020 = three2020[['Subjects', 'Subj % 2020']]

# rename columns and sort values
three2020 = three2020.rename(columns={'Subj % 2020': 'Three Subjects % 2020'})
three2020 = three2020.sort_values('Three Subjects % 2020', ascending=False).reset_index(drop=True)

one2020 = diff_one_df2023
one2020 = one2020[['Subjects', 'Subj % 2020']]

# rename columns and sort values 
one2020 = one2020.rename(columns={'Subjects': 'One Subjects', 'Subj % 2020': 'One Subjects % 2020'})
one2020 = one2020.sort_values('One Subjects % 2020', ascending=False).reset_index(drop=True)

#comp_df = pd.merge(three2023, one2023, how='left', on='Subjects')
comp_df2020 = pd.concat([three2020, one2020], axis=1)
comp_df2020 = comp_df2020.head(15)
comp_df2020

In [263]:
# plotting sorted  by 2023 Diff 2018 on all three subjects (largest to smallest positive change)
ThreeSHChange2018 = diff_three_df2023.copy()
ThreeSHChange2018 = ThreeSHChange2018.rename(columns={"Subj % 2018": "2018 Subj Collection %", "Subj % 2023": "2023 Subj Collection %"})
# '2018 Subj Collection %'
# normalize decimals to percentage
ThreeSHChange2018['2018 Subj Collection %'] = ThreeSHChange2018['2018 Subj Collection %'] * 100
ThreeSHChange2018['2023 Subj Collection %'] = ThreeSHChange2018['2023 Subj Collection %'] * 100

# subtract years to see change
ThreeSHChange2018['Subj Num Growth Change'] = ThreeSHChange2018['2023 Subj Collection %'] - ThreeSHChange2018['2018 Subj Collection %']

# num checkouts
ThreeSHChange2018['2018 Loan Number'] = (ThreeSHChange2018['2018 Subj Collection %'] / 100) * unique_loans
ThreeSHChange2018['2023 Loan Number'] = (ThreeSHChange2018['2023 Subj Collection %'] / 100) * unique_loans
ThreeSHChange2018['Loan Number Change'] = ThreeSHChange2018['2023 Loan Number'] - ThreeSHChange2018['2018 Loan Number'] 


#ThreeSHChange2018 = ThreeSHChange2018.sort_values('Subj% Change', ascending=False)

#multiplier
ThreeSHChange2018['Subj Multi Growth Factor'] = ThreeSHChange2018['2023 Subj Collection %'] / ThreeSHChange2018['2018 Subj Collection %']
ThreeSHChange2018 = ThreeSHChange2018[['Subjects', '2018 Loan Number', '2023 Loan Number', 'Loan Number Change', '2018 Subj Collection %', '2023 Subj Collection %', 'Subj Num Growth Change', 'Subj Multi Growth Factor']]


# sort table by growth
ThreeSHChange2018 = ThreeSHChange2018.sort_values('Subj Num Growth Change', ascending=False)

# sort table by subj num growth change
#ThreeSHChange2018 = ThreeSHChange2018.sort_values('Subj Multi Growth Factor', ascending=False).reset_index(drop=True)

# reindex to start at 1
ThreeSHChange2018 = ThreeSHChange2018.head(10)
ThreeSHChange2018.index = ThreeSHChange2018.index + 1

# create a table title
#ThreeSHChange2018 = ThreeSHChange2018.style.set_caption('Table 1: Top 10 Subject Headings Growth From 2018 to 2023')
ThreeSHChange2018

,Subjects,2018 Loan Number,2023 Loan Number,Loan Number Change,2018 Subj Collection %,2023 Subj Collection %,Subj Num Growth Change,Subj Multi Growth Factor
1,Architecture--Espagne--20e siècle--Périodiques.,154.442175,311.501482,157.059306,0.750156,1.513024,0.762868,2.016946
2,Architecture--Spain--Periodicals.,155.872196,311.501482,155.629286,0.757102,1.513024,0.755922,1.998442
3,"Architecture, Domestic--Designs and plans",38.610544,105.974731,67.364187,0.187539,0.514740,0.327201,2.744710
4,Architecture domestique.,4.290060,67.438465,63.148405,0.020838,0.327562,0.306724,15.719701
5,"Architecture, Modern--20th century--Designs an...",51.480725,112.397442,60.916717,0.250052,0.545937,0.295885,2.183292
6,Architecture--Environmental aspects,85.801209,138.088286,52.287077,0.416753,0.670722,0.253969,1.609398
7,Architecture--Japan--History--20th century,58.630826,105.974731,47.343905,0.284782,0.514740,0.229959,1.807492
8,Architecture--Human factors,72.931027,118.820153,45.889126,0.354240,0.577133,0.222893,1.629213
9,Sustainable architecture,77.221088,115.608797,38.387710,0.375078,0.561535,0.186457,1.497114
10,Architecture,181.612558,218.372173,36.759615,0.882128,1.060677,0.178549,1.202407

# plotting sorted  by 2023 Diff 2018 on all three subjects (largest to smallest positive change)
ThreeSHChange2018 = diff_three_df2023.rename(columns={"2023 Diff 2018": "2023 Growth %"})
ThreeSHChange2018 = ThreeSHChange2018.sort_values('2023 Growth %', ascending=False)

# normalize decimals to percentage
ThreeSHChange2018['Subj % 2018'] = ThreeSHChange2018['Subj % 2018'] * 100
ThreeSHChange2018['Subj % 2023'] = ThreeSHChange2018['Subj % 2023'] * 100

# limit to top 20 growing subject headings and select 2018 and 2023 years only
colors = colors=['darkgray','gray']
ThreeSHChange2018 = ThreeSHChange2018.head(20).sort_values('2023 Growth %', ascending=True).plot(x="Subjects", y=['Subj % 2018', 'Subj % 2023'], kind="barh", color=colors) 
ThreeSHChange2018.set_title('Figure 1: Top 20 Subject Headings Growth From 2018 to 2023')

ThreeSHChange2018

In [ ]:
# plotting sorted  by 2023 Diff 2018 on all three subjects (largest to smallest positive change)
ThreeSHGrowth2023 = diff_three_df2023.copy()
ThreeSHGrowth2023 = ThreeSHGrowth2023.rename(columns={"Subj % 2018": "2018 Subj Collection %", 
                                                      "Subj % 2020": "2020 Subj Collection %", 
                                                      "Subj % 2023": "2023 Subj Collection %"})
# '2018 Subj Collection %'
# normalize decimals to percentage
ThreeSHGrowth2023['2018 Subj Collection %'] = ThreeSHGrowth2023['2018 Subj Collection %'] * 100
ThreeSHGrowth2023['2020 Subj Collection %'] = ThreeSHGrowth2023['2020 Subj Collection %'] * 100
ThreeSHGrowth2023['2023 Subj Collection %'] = ThreeSHGrowth2023['2023 Subj Collection %'] * 100

# subtract years to see change
ThreeSHGrowth2023['Subj Num Growth Change'] = ThreeSHGrowth2023['2023 Subj Collection %'] - ThreeSHGrowth2023['2020 Subj Collection %']

# num checkouts
ThreeSHGrowth2023['2020 Loan Number'] = (ThreeSHGrowth2023['2020 Subj Collection %'] / 100) * unique_loans
ThreeSHGrowth2023['2023 Loan Number'] = (ThreeSHGrowth2023['2023 Subj Collection %'] / 100) * unique_loans
ThreeSHGrowth2023['Loan Number Change'] = ThreeSHGrowth2023['2023 Loan Number'] - ThreeSHGrowth2023['2020 Loan Number'] 


#ThreeSHChange2018 = ThreeSHChange2018.sort_values('Subj% Change', ascending=False)

#multiplier
ThreeSHGrowth2023['Subj Multi Growth Factor'] = ThreeSHGrowth2023['2023 Subj Collection %'] / ThreeSHGrowth2023['2020 Subj Collection %']
ThreeSHGrowth2023 = ThreeSHGrowth2023[['Subjects', 'Loan Number Change', '2018 Subj Collection %','2020 Subj Collection %', '2023 Subj Collection %', 'Subj Num Growth Change', 'Subj Multi Growth Factor']]


# sort table by growth
ThreeSHGrowth2023 = ThreeSHGrowth2023.sort_values('Subj Num Growth Change', ascending=False)

# sort table by subj num growth change
#ThreeSHChange2018 = ThreeSHChange2018.sort_values('Subj Multi Growth Factor', ascending=False).reset_index(drop=True)

# reindex to start at 1
ThreeSHGrowth2023 = ThreeSHGrowth2023.head(10).reset_index(drop=True)
ThreeSHGrowth2023.index = ThreeSHGrowth2023.index + 1

# create a table title
#ThreeSHChange2018 = ThreeSHChange2018.style.set_caption('Table 1: Top 10 Subject Headings Growth From 2018 to 2023')
ThreeSHGrowth2023

# plotting sorted  by 2023 Diff 2018 on all three subjects (largest to smallest positive change)
ThreeSHGrowth2023 = diff_three_df2023.rename(columns={"2023 Diff 2020": "2023 Growth %"})
ThreeSHGrowth2023 = ThreeSHGrowth2023.sort_values('2023 Growth %', ascending=False)

# normalize decimals to percentage
ThreeSHGrowth2023['Subj % 2018'] = ThreeSHGrowth2023['Subj % 2018'] * 100
ThreeSHGrowth2023['Subj % 2020'] = ThreeSHGrowth2023['Subj % 2020'] * 100
ThreeSHGrowth2023['Subj % 2023'] = ThreeSHGrowth2023['Subj % 2023'] * 100

# subtract years to see change
ThreeSHGrowth2023['Subj% Change'] = ThreeSHGrowth2023['Subj % 2023'] - ThreeSHGrowth2023['Subj % 2020']

#ThreeSHChange2018 = ThreeSHChange2018.sort_values('Subj% Change', ascending=False)
ThreeSHGrowth2023 = ThreeSHGrowth2023[['Subjects', 'Subj % 2018', 'Subj % 2020', 'Subj % 2023', 'Subj% Change']]

# reindex to start at 1
ThreeSHGrowth2023 = ThreeSHGrowth2023.head(10).reset_index(drop=True)
ThreeSHGrowth2023.index = ThreeSHGrowth2023.index + 1

# create a table title
ThreeSHGrowth2023 = ThreeSHGrowth2023.style.set_caption('Table 2: Top 10 Subject Headings Growth From 2020 to 2023')
ThreeSHGrowth2023

# plotting sorted by 2023 Diff 2018 on all three subjects (largest to smallest positive change)
ThreeSHGrowth2023 = diff_three_df2023.rename(columns={"2023 Diff 2020": "2023 Growth %"})
ThreeSHGrowth2023 = ThreeSHGrowth2023.sort_values('2023 Growth %', ascending=False)

# normalize decimals to percentage
ThreeSHGrowth2023['Subj % 2018'] = ThreeSHGrowth2023['Subj % 2018'] * 100
ThreeSHGrowth2023['Subj % 2020'] = ThreeSHGrowth2023['Subj % 2020'] * 100
ThreeSHGrowth2023['Subj % 2023'] = ThreeSHGrowth2023['Subj % 2023'] * 100

# limit to top 20 growing subject headings and select 2018, 2020, and 2023 years
colors = colors=['darkgray', 'gray','dimgray']
ThreeSHGrowth2023 = ThreeSHGrowth2023.head(20).sort_values('2023 Growth %', ascending=True).plot(x="Subjects", y=['Subj % 2018', 'Subj % 2020', 'Subj % 2023'], kind="barh", color=colors) 
ThreeSHGrowth2023.set_title('Figure 2: Top 20 Subject Headings Growth From 2020 to 2023')

ThreeSHGrowth2023

In [ ]:
# plotting sorted  by 2023 Diff 2018 on all three subjects (largest to smallest positive change)
ThreeSHDec2023 = diff_three_df2023.copy()
ThreeSHDec2023 = ThreeSHDec2023.rename(columns={"Subj % 2018": "2018 Subj Collection %", 
                                                      "Subj % 2020": "2020 Subj Collection %", 
                                                      "Subj % 2023": "2023 Subj Collection %"})
# '2018 Subj Collection %'
# normalize decimals to percentage
ThreeSHDec2023['2018 Subj Collection %'] = ThreeSHDec2023['2018 Subj Collection %'] * 100
ThreeSHDec2023['2020 Subj Collection %'] = ThreeSHDec2023['2020 Subj Collection %'] * 100
ThreeSHDec2023['2023 Subj Collection %'] = ThreeSHDec2023['2023 Subj Collection %'] * 100

# subtract years to see change
ThreeSHDec2023['Subj Num Growth Change'] = ThreeSHDec2023['2023 Subj Collection %'] - ThreeSHDec2023['2018 Subj Collection %']

# num checkouts
ThreeSHDec2023['2018 Loan Number'] = (ThreeSHDec2023['2020 Subj Collection %'] / 100) * unique_loans
ThreeSHDec2023['2023 Loan Number'] = (ThreeSHDec2023['2023 Subj Collection %'] / 100) * unique_loans
ThreeSHDec2023['Loan Number Change'] = ThreeSHDec2023['2023 Loan Number'] - ThreeSHDec2023['2018 Loan Number'] 


#ThreeSHChange2018 = ThreeSHChange2018.sort_values('Subj% Change', ascending=False)

#multiplier
ThreeSHDec2023['Subj Multi Growth Factor'] = ThreeSHDec2023['2023 Subj Collection %'] / ThreeSHDec2023['2018 Subj Collection %']
ThreeSHDec2023 = ThreeSHDec2023[['Subjects', 'Loan Number Change', '2018 Subj Collection %','2020 Subj Collection %', '2023 Subj Collection %', 'Subj Num Growth Change', 'Subj Multi Growth Factor']]


# sort table by growth
ThreeSHDec2023 = ThreeSHDec2023.sort_values('Subj Num Growth Change', ascending=True)

# sort table by subj num growth change
#ThreeSHChange2018 = ThreeSHChange2018.sort_values('Subj Multi Growth Factor', ascending=False).reset_index(drop=True)

# reindex to start at 1
ThreeSHDec2023 = ThreeSHDec2023.head(10).reset_index(drop=True)
ThreeSHDec2023.index = ThreeSHDec2023.index + 1

# create a table title
#ThreeSHDec2020 = ThreeSHDec2020.style.set_caption('Table 3: Top 10 Decreasing Subject Headings From 2020 to 2023')
ThreeSHDec2023

In [ ]:
# plotting sorted  by 2023 Diff 2018 on all three subjects (largest to smallest positive change)
ThreeSHDec2020 = diff_three_df2023.copy()
ThreeSHDec2020 = ThreeSHDec2020.rename(columns={"Subj % 2018": "2018 Subj Collection %", 
                                                      "Subj % 2020": "2020 Subj Collection %", "Subj % 2023": "2023 Subj Collection %"})
# '2018 Subj Collection %'
# normalize decimals to percentage
ThreeSHDec2020['2018 Subj Collection %'] = ThreeSHDec2020['2018 Subj Collection %'] * 100
ThreeSHDec2020['2020 Subj Collection %'] = ThreeSHDec2020['2020 Subj Collection %'] * 100
ThreeSHDec2020['2023 Subj Collection %'] = ThreeSHDec2020['2023 Subj Collection %'] * 100

# subtract years to see change
ThreeSHDec2020['Subj Num Growth Change'] = ThreeSHDec2020['2023 Subj Collection %'] - ThreeSHDec2020['2020 Subj Collection %']

# num checkouts
ThreeSHDec2020['2020 Loan Number'] = (ThreeSHDec2020['2020 Subj Collection %'] / 100) * unique_loans
ThreeSHDec2020['2023 Loan Number'] = (ThreeSHDec2020['2023 Subj Collection %'] / 100) * unique_loans
ThreeSHDec2020['Loan Number Change'] = ThreeSHDec2020['2023 Loan Number'] - ThreeSHDec2020['2020 Loan Number'] 


#ThreeSHChange2018 = ThreeSHChange2018.sort_values('Subj% Change', ascending=False)

#multiplier
ThreeSHDec2020['Subj Multi Growth Factor'] = ThreeSHDec2020['2023 Subj Collection %'] / ThreeSHDec2020['2020 Subj Collection %']
ThreeSHDec2020 = ThreeSHDec2020[['Subjects', 'Loan Number Change', '2018 Subj Collection %','2020 Subj Collection %', '2023 Subj Collection %', 'Subj Num Growth Change', 'Subj Multi Growth Factor']]


# sort table by growth
ThreeSHDec2020 = ThreeSHDec2020.sort_values('Subj Num Growth Change', ascending=True)

# sort table by subj num growth change
#ThreeSHChange2018 = ThreeSHChange2018.sort_values('Subj Multi Growth Factor', ascending=False).reset_index(drop=True)

# reindex to start at 1
ThreeSHDec2020 = ThreeSHDec2020.head(10).reset_index(drop=True)
ThreeSHDec2020.index = ThreeSHDec2020.index + 1

# create a table title
#ThreeSHDec2020 = ThreeSHDec2020.style.set_caption('Table 3: Top 10 Decreasing Subject Headings From 2020 to 2023')
ThreeSHDec2020

# plotting sorted  by 2023 Diff 2018 on all three subjects (largest to smallest positive change)
ThreeSHDec2020 = diff_three_df2023.rename(columns={"2023 Diff 2020": "2023 Decline %"})
ThreeSHDec2020 = ThreeSHDec2020.sort_values('2023 Decline %', ascending=True)

# normalize decimals to percentage
ThreeSHDec2020['Subj % 2018'] = ThreeSHDec2020['Subj % 2018'] * 100
ThreeSHDec2020['Subj % 2020'] = ThreeSHDec2020['Subj % 2020'] * 100
ThreeSHDec2020['Subj % 2023'] = ThreeSHDec2020['Subj % 2023'] *100

# subtract years to see change
ThreeSHDec2020['Subj% Change'] = ThreeSHDec2020['Subj % 2023'] - ThreeSHDec2020['Subj % 2020']

#ThreeSHChange2018 = ThreeSHChange2018.sort_values('Subj% Change', ascending=False)
ThreeSHDec2020 = ThreeSHDec2020[['Subjects', 'Subj % 2018', 'Subj % 2020', 'Subj % 2023', 'Subj% Change']]

# reindex to start at 1
ThreeSHDec2020 = ThreeSHDec2020.head(10).reset_index(drop=True)
ThreeSHDec2020.index = ThreeSHDec2020.index + 1

# create a table title
ThreeSHDec2020 = ThreeSHDec2020.style.set_caption('Table 3: Top 10 Decreasing Subject Headings From 2020 to 2023')
ThreeSHDec2020

# plotting sorted  by 2023 Diff 2018 on all there subjects (largest to smallest negative change)
ThreeSHDec2020 = diff_three_df2023.rename(columns={"2023 Diff 2020": "2023 Decline %"})
ThreeSHDec2020 = ThreeSHDec2020.sort_values('2023 Decline %', ascending=True)

# normalize decimals to percentage
ThreeSHDec2020['Subj % 2018'] = ThreeSHDec2020['Subj % 2018'] * 100
ThreeSHDec2020['Subj % 2020'] = ThreeSHDec2020['Subj % 2020'] * 100
ThreeSHDec2020['Subj % 2023'] = ThreeSHDec2020['Subj % 2023'] * 100

# limit to top 20 decreasing subject headings and select 2018, 2020, and 2023 years
colors = colors=['darkgray', 'gray', 'dimgray']
ThreeSHDec2020 = ThreeSHDec2020.head(20).sort_values('2023 Decline %', ascending=False).plot(x="Subjects", y=['Subj % 2018', 'Subj % 2020', 'Subj % 2023'], kind="barh", color=colors) 
ThreeSHDec2020.set_title('Figure 3: Top 20 Decreasing Subject Headings From 2020 to 2023')

ThreeSHDec2020

In [ ]:
# Look up how much the subject headingg Architects--Japan--Interviews. grew from 2018 to 2020
print('The number of Japanese interviews in 2018:', len(three_df[(three_df['Subjects'] == 'Architects--Japan--Interviews.') & (three_df["Date"] == '2018')])), print('The number of Japanese interviews in 2020:',  len(three_df[(three_df['Subjects'] == 'Architects--Japan--Interviews.') & (three_df["Date"] == '2020')]))

In [ ]:
# look up Buildings--Remodeling for other use to see how much it grew from 2020 to 2023 
diff_three_df2023[(diff_three_df2023['Subjects'] == 'Buildings--Remodeling for other use')]